### ISSUE TITLE
Ophyd device for DG-645

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#874]
I noticed the DG-645 is listed here but I don't see any issues or commits that add it. Happy to do it myself, just checking before I get started in case it's been done already. Thanks!

_Originally posted by @canismarko in https://github.com/BCDA-APS/apstools/issues/489#issuecomment-1686950832_

**Comment by canismarko** [comment]
Sounds good. I'll get on it.

**Comment by canismarko** [comment]
@prjemian, putting this here so it's documented in case anyone runs into this problem.

The DG-645 support I put in the PR uses a subclass of ophyd.EpicsSignal: ``EpicsSignalWithIO``.

I came across an edge case where if you use the DG645 delay device with ``ophyd.sim.make_fake_device`` it doesn't recognize ``EpicsSignalWithIO``, and so doesn't fake it. You can still create a fake device from it, but if you access any of the signals that use the custom ``EpicsSignalWithIO`` class, it will time out because the PV is not available:

```python
from ophyd.sim import make_fake_device
from apstools.devices.delay import DG645Delay

@pytest.fixture()
def fake_delay():
    Delay = make_fake_device(DG645Delay)
    return Delay("255id:DG645:", name="fake_delay")

def test_fake_delay(fake_delay):
    fake_delay.label.get()  # Success, since it's a regular EpicsSignal
    fake_delay.dhcp_state.get()  # TimeoutError, since it's an EpicsSignalWithIO
```

Ophyd sim module builds a cache of signals that it knows how to fake, so we can add our own fake signal to the cache before calling ``make_fake_device(DG645Delay)``. The solution then, assuming you use pytest, is to place the following in *conftest.py*

```python
from ophyd.sim import FakeEpicsSignal, fake_device_cache

from apstools.devices.delay import EpicsSignalWithIO

class FakeEpicsSignalWithIO(FakeEpicsSignal):
    """An EPICS signal that simply uses the DG-645 convention of
    'AO' being the setpoint and 'AI' being the read-back."""
    _metadata_keys = EpicsSignalWithIO._metadata_keys

    def __init__(self, prefix, **kwargs):
        super().__init__(f"{prefix}I", write_pv=f"{prefix}O", **kwargs)


fake_device_cache[EpicsSignalWithIO] = FakeEpicsSignalWithIO
```
